version: '2'

services:
  codeaday-server:
    container_name: codeaday-server
    restart: always
    image: python:3.6-buster
    # command: /usr/local/bin/gunicorn --workers=4 --bind :8000 cad_server.wsgi:application --reload --log-level info
    command: tail -f /dev/null
    volumes:
      - project:/cad_server
      - log:/var/log/codeaday/
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - codeaday-db
      - codeaday-redis
    networks:
      - default
  codeaday-redis:
    image: redis:latest
    restart: always
    container_name: codeaday-redis
    networks:
      - default
  codeaday-db:
    container_name: codeaday-db
    restart: always
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hollyshit123!@#
      MYSQL_USER: codeaday
      MYSQL_PASSWORD: hollyshit123
      MYSQL_DATABASE: codeaday
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
  codeaday-nginx:
    container_name: codeaday-nginx
    restart: always
    image: nginx:latest
    environment:
      VIRTUAL_HOST: codeaday.qiwihui.com
      LETSENCRYPT_HOST: codeaday.qiwihui.com
      LETSENCRYPT_EMAIL: qwh005007@gmail.com
    ports:
      - "80"
    volumes:
      - project:/cad_server
      - frontend:/cad_fe
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - codeaday-server
    depends_on:
      - codeaday-server
    networks:
      - default

volumes:
  project:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/projects/codeaday/cad_server'
  mysql_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/projects/codeaday_data/mysql'
  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/projects/codeaday/cad_fe/dist'
  log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/codeaday/'
# networks:
#   codeaday-network:
#     driver: bridge

networks:
  default:
    external:
      name: codeaday-network