version: '2'

services:
  db:
    container_name: codeaday-db
    restart: always
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hollyshit123!@#
      MYSQL_USER: codeaday
      MYSQL_PASSWORD: hollyshit123
      MYSQL_DATABASE: codeaday
    volumes:
      - /data/mysql:/var/lib/mysql