on:
  push:
    branches: master

name: deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: just say hello
      uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: 'CodeADay'
