name: deploy codedays frontend

on:
  push:
    paths:
      - 'cad_fe/*'
      - '.github/workflows/deploy_fe.yml'
    branches:    
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm install, build, and test
        run: |
          cd cad_fe
          npm install
          npm run build
          rm dist/*/*.map

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: cad_fe_dist
          path: cad_fe/dist
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - run: rm -rf /opt/projects/codedays/cad_fe/dist/*
      - name: Download built package
        uses: actions/download-artifact@v1
        with:
          name: cad_fe_dist
          path: /opt/projects/codedays/cad_fe/dist/
